
CREATE DATABASE ggchamp;
USE ggchamp;



CREATE TABLE usuario (

  ID INT NOT NULL AUTO_INCREMENT,

  NOMBRE VARCHAR(20) NOT NULL,

  MAIL VARCHAR(100) NOT NULL UNIQUE,

  CONTRASEÑA VARCHAR(255) NOT NULL,

  ROL ENUM('usuario', 'administrador') NOT NULL,
  
  ACTIVO BOOLEAN NOT NULL DEFAULT TRUE,

  PRIMARY KEY (ID)

);


CREATE TABLE inscripcion (

  ID INT NOT NULL AUTO_INCREMENT,

  IDPARTICIPANTE INT NOT NULL,

  IDTORNEO INT NOT NULL,

  IDEQUIPO INT NULL,

  PRIMARY KEY (ID),

  UNIQUE (IDPARTICIPANTE, IDTORNEO),

  FOREIGN KEY (IDPARTICIPANTE) REFERENCES usuario (ID),

  FOREIGN KEY (IDTORNEO) REFERENCES torneo (ID),

  FOREIGN KEY (IDEQUIPO) REFERENCES equipo (ID) ON DELETE SET NULL

);

CREATE TABLE torneo (

  ID INT NOT NULL AUTO_INCREMENT,

  IDORGANIZADOR INT NOT NULL,

  NOMBRE VARCHAR(20) NOT NULL,

  FECHA DATE NOT NULL,
  
  FORMATO VARCHAR(10) NOT NULL,
  
  DISCIPLINA ENUM('futbol','basquetbol','tenis','tenis_mesa','voleibol','ajedrez','damas','uno',
  'fifa','valorant','league_of_legends','counter_strike','rocket_league') NOT NULL,
  
  LUGAR VARCHAR (40) NOT NULL,
  
  PARTICIPACION ENUM('solo', 'equipo') NOT NULL,
  
  CONTRASENA VARCHAR(255) NOT NULL,	
  
  FOREIGN KEY (FORMATO) REFERENCES formato(NOMBRE),
  PRIMARY KEY (ID),
  FOREIGN KEY (IDORGANIZADOR) REFERENCES usuario (ID)

);



CREATE TABLE equipo (

  ID INT NOT NULL AUTO_INCREMENT,

  NOMBRE VARCHAR(20) NOT NULL,

  IDTORNEO INT NOT NULL,

  PRIMARY KEY (ID),

  FOREIGN KEY (IDTORNEO) REFERENCES torneo (ID)

);


CREATE TABLE competidor (

  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

  IDTORNEO INT NOT NULL,

  TIPO ENUM('individual', 'equipo') NOT NULL,

  IDINSCRIPCION INT NULL,

  IDEQUIPO INT NULL,

  FOREIGN KEY (IDTORNEO) REFERENCES torneo (ID) ON DELETE CASCADE,

  FOREIGN KEY (IDINSCRIPCION) REFERENCES inscripcion (ID) ON DELETE CASCADE,

  FOREIGN KEY (IDEQUIPO) REFERENCES equipo (ID) ON DELETE CASCADE
);



CREATE TABLE ronda (

  ID INT NOT NULL AUTO_INCREMENT,

  NUMERO INT NOT NULL,

  IDTORNEO INT NOT NULL,

  PRIMARY KEY (ID),

  UNIQUE (NUMERO, IDTORNEO),

  FOREIGN KEY (IDTORNEO) REFERENCES torneo (ID)
);



CREATE TABLE partido (

  ID INT NOT NULL AUTO_INCREMENT,

  NUMERO INT NOT NULL,

  IDRONDA INT NOT NULL,

  RESULTADO VARCHAR(40) DEFAULT NULL,

  IDCOMPETIDOR_1 INT NULL,

  IDCOMPETIDOR_2 INT NULL,

  IDEQUIPO_1 INT NULL,

  IDEQUIPO_2 INT NULL,

  PRIMARY KEY (ID),

  UNIQUE (NUMERO, IDRONDA),

  FOREIGN KEY (IDCOMPETIDOR_1) REFERENCES usuario (ID),

  FOREIGN KEY (IDCOMPETIDOR_2) REFERENCES usuario (ID),

  FOREIGN KEY (IDEQUIPO_1) REFERENCES equipo (ID),

  FOREIGN KEY (IDEQUIPO_2) REFERENCES equipo (ID),

  FOREIGN KEY (IDRONDA) REFERENCES ronda (ID)
);


CREATE TABLE formato(
NOMBRE ENUM('suizo', 'liga', 'eliminacion') NOT NULL PRIMARY KEY,
ACTIVO BOOLEAN NOT NULL DEFAULT TRUE
);



CREATE TABLE registro (

  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

  ACCION VARCHAR(100) NOT NULL,
  
  IDUSUARIO INT NOT NULL,

  FECHA DATETIME NOT NULL,

  FOREIGN KEY (IDUSUARIO) REFERENCES usuario (ID)
);

INSERT INTO formato (NOMBRE, ACTIVO) VALUES
('suizo', TRUE),
('liga', TRUE),
('eliminacion', TRUE);