DROP DATABASE ggchamp;
CREATE DATABASE ggchamp;
USE ggchamp;



CREATE TABLE usuario (

  ID INT NOT NULL AUTO_INCREMENT,

  NOMBRE VARCHAR(20) NOT NULL,

  MAIL VARCHAR(100) NOT NULL UNIQUE,

  CONTRASEÑA VARCHAR(255) NOT NULL,

  ROL ENUM('usuario', 'administrador') NOT NULL,

  PRIMARY KEY (ID)

);


delete from usuario where ID=1;

update usuario set NOMBRE='a', MAIL='a', CONTRASEÑA='a' where id=1;
insert into usuario( ID, NOMBRE,MAIL ,CONTRASEÑA, ROL) values (1, 'gamer','dfkofd@gmail.com','frgddthh','MAESTRO');

insert into usuario( ID, NOMBRE,MAIL ,CONTRASEÑA, ROL) values (23, 'gamer','dosfkofd@gmail.com','frgddthh','MAESTRO');

select * from usuario;
CREATE TABLE torneo (

  ID INT NOT NULL AUTO_INCREMENT,

  IDORGANIZADOR INT NOT NULL,

  NOMBRE VARCHAR(20) NOT NULL,

  FECHA DATE NOT NULL,

  FORMATO ENUM('suizo', 'liga', 'eliminacion') NOT NULL,

  DISCIPLINA ENUM('deporte', 'mesa') NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (IDORGANIZADOR) REFERENCES usuario (ID)

);



CREATE TABLE equipo (

  ID INT NOT NULL AUTO_INCREMENT,

  NOMBRE VARCHAR(20) NOT NULL,

  IDTORNEO INT NOT NULL,

  PRIMARY KEY (ID),

  FOREIGN KEY (IDTORNEO) REFERENCES torneo (ID)

);



CREATE TABLE inscripcion (

  ID INT NOT NULL AUTO_INCREMENT,

  IDPARTICIPANTE INT NOT NULL,

  IDTORNEO INT NOT NULL,

  IDEQUIPO INT NULL,

  PRIMARY KEY (ID),

  UNIQUE (IDPARTICIPANTE, IDTORNEO),

  FOREIGN KEY (IDPARTICIPANTE) REFERENCES usuario (ID),

  FOREIGN KEY (IDTORNEO) REFERENCES torneo (ID),

  FOREIGN KEY (IDEQUIPO) REFERENCES equipo (ID)

);



CREATE TABLE ronda (

  ID INT NOT NULL AUTO_INCREMENT,

  NUMERO INT NOT NULL,

  IDTORNEO INT NOT NULL,

  PRIMARY KEY (ID),

  UNIQUE (NUMERO, IDTORNEO),

  FOREIGN KEY (IDTORNEO) REFERENCES torneo (ID)

);



CREATE TABLE partido (

  ID INT NOT NULL AUTO_INCREMENT,

  NUMERO INT NOT NULL,

  IDRONDA INT NOT NULL,

  RESULTADO VARCHAR(40) DEFAULT NULL,

  IDCOMPETIDOR_1 INT NULL,

  IDCOMPETIDOR_2 INT NULL,

  IDEQUIPO_1 INT NULL,

  IDEQUIPO_2 INT NULL,

  PRIMARY KEY (ID),

  UNIQUE (NUMERO, IDRONDA),

  FOREIGN KEY (IDCOMPETIDOR_1) REFERENCES usuario (ID),

  FOREIGN KEY (IDCOMPETIDOR_2) REFERENCES usuario (ID),

  FOREIGN KEY (IDEQUIPO_1) REFERENCES equipo (ID),

  FOREIGN KEY (IDEQUIPO_2) REFERENCES equipo (ID),

  FOREIGN KEY (IDRONDA) REFERENCES ronda (ID)

);



CREATE TABLE registro (

  ID INT NOT NULL AUTO_INCREMENT,

  ACCION VARCHAR(100) NOT NULL,

  FECHA DATETIME NOT NULL,

  IDUSUARIO INT NOT NULL,

  PRIMARY KEY (ID),

  FOREIGN KEY (IDUSUARIO) REFERENCES usuario (ID)

);
select * from usuario